### PR TITLE
rust-ui-template: use crossterm as the key / terminal backend

### PR DESCRIPTION
**Pull request by amtoine**
related to 
- https://github.com/amtoine/nu_plugin_explore/issues/1

> **Warning**
> very important caveat:
> - this plugin won't work with the latest versions of Nushell => i'll work on that when i upgrade the dependencies
> - use Nushell version `0.84.0` to make sure the plugin launches

### major
- make everything public for simplicity, i.e. there is no `pub (super)` or `pub (crate)` anymore, only nothing or `pub`
- use `KeyCode` from `crossterm` instead of `Key` from `console` (template requirement)
- use `foo<B: Backend>(frame: &mut Frame<'_, B>, ...)` instead of `foo(frame: &mut Frame<CrosstermBackend<console::Term>>, ...)` for rendering
- add a `size` method to `Tui` to change the size of the editor dynamically
- use the following snippet when there is an error to hold the application loop until there is a key stroke and avoid refreshing as soon as there is a terminal tick, which makes the error disappear immediately
```rust
loop {
    if let Event::Key(_) = tui.events.next()? {
        break;
    }
}
```

### minor / refactoring
- remove out-of-date documentation => this will have to be tackled probably by adding lint warnings for missing documentation
- move all the rendering from `tui.rs` to `ui.rs` (template file / only renaming)
- replace `terminal.rs` with `tui.rs` (template)
- use `event.rs` and `tui.rs` as-is (template)
- apply minor tweaks to the template, e.g. removing useless comments in the main loop and renaming `tui` to `ratatui`

> **Note**
> i'll leave the documentation and the `pub` visibility issues to another time

### CODE REVIEW

**Comment by amtoine** [comment]
@fdncred
can you try this branch with Nushell `0.84.0` and see if that fixes your issue?
it works with my system almost as before :crossed_fingers:

**Comment by amtoine** [comment]
also i'm concerned about the last caveat about *peeking subdata* :thinking: 
it's quite annoying :sweat_smile:

**Comment by fdncred** [comment]
I don't have 0.84.0 installed anywhere. I try to stay on the latest main. I'd be excited to test it though if it were on 0.84.1.

**Comment by amtoine** [comment]
> I don't have 0.84.0 installed anywhere. I try to stay on the latest main. I'd be excited to test it though if it were on 0.84.1.
>
i wanted to know if using the `rust-tui-template` could solve the issue you encountered by using `crossterm` instead of `console` before moving on to upgrading to `0.84.1` :confused: 

could you just try the following? :innocent: 
- install and register the plugin from this PR
- checkout Nushell 0.84.0
- try `explore` from inside `cargo run`

that'd be amazing :blush:

**Comment by fdncred** [comment]
This works except for one thing. On Windows 1 keypress = 2 with crossterm because there is a press and release event. You have to do something like this

https://github.com/ratatui-org/ratatui-async-template/blob/f992a061c04ff05dd03a5f0b5d6ade6370d9aae2/src/event.rs#L62C1-L66

Other than that, it works fine.

**Comment by amtoine** [comment]
> This works except for one thing.
> ...
> Other than that, it works fine.
>
ooh i'm happy this fixes the issue :relieved: 

> On Windows 1 keypress = 2 with crossterm because there is a press and release event. You have to do something like this
> 
> https://github.com/ratatui-org/ratatui-async-template/blob/f992a061c04ff05dd03a5f0b5d6ade6370d9aae2/src/event.rs#L62C1-L66
> 
very good catch, let me fix that right now :wink:

**Pull request merged**
